### ISSUE TITLE
Error in (local) TACSim_in_C.py

### ISSUE THREAD

**Issue by shoaloak** [caesar0301/graphsim#6]
Hi Chen,

Thank you for making graphsim. I was wondering if i could use it without root access on a machine.
Therefore, I compiled libtacsim locally and modified TACSim_in_C.py to find the local libs.

However, when i run print(gs.tacsim_combined_in_C(G1, G2)) my program crashes

I am using python2.7.14, graphsim is installed in a virtual environment venv, and here is the trace, any tips?

`Traceback (most recent call last):
  File "compare_graph.py", line 22, in <module>
    print(gs.tacsim_combined_in_C(G1, G2))
  File "/home/shoaloak/src/git/funky-nodes/venv/lib/python2.7/site-packages/graphsim/iter/TACSim_in_C.py", line 180, in tacsim_combined_in_C
    As, At = node_edge_adjacency(G1)
  File "/home/shoaloak/src/git/funky-nodes/venv/lib/python2.7/site-packages/typedecorator/__init__.py", line 389, in wrapper
    return fn(*args, **kwargs)
  File "/home/shoaloak/src/git/funky-nodes/venv/lib/python2.7/site-packages/graphsim/iter/TACSim.py", line 195, in node_edge_adjacency
    node_index[nodes[i]] = i
TypeError: unhashable type: 'dict'`

**Comment by caesar0301** [comment]
Hi, I picked up root cause that lay in the newest version of networkx 2.0. I workaround this issue by specifying the netowrkx==1.11, rather than the newest 2.0.

For the root issues, please read updated readme to avoid permission request.
